#!/bin/bash

cowPath="/usr/share/cowsay"
cowfiles=$(find $cowPath -name '*.cow');

cowfilesList=(`echo $cowfiles`);


len=${#cowfilesList[@]}
# using $RANDOM special bash variable
randIndex=$((RANDOM%len))

cowfile=${cowfilesList[$randIndex]}

mstart=' _______'
mend=' -------'
if [ -x `which fortune` -a -x `which cowsay` ]; then
  echo "Using cow file: $cowfile"
  fortune -ac | cowthink -n -f $cowfile | sed "/$mstart/,/$mend/ s/^(\\|)$//g"
fi;

